# TP de session : Hotel Cancellation Prediction

## Projet de classification

Objectif : développer un modèle de classification capable de prédire si une réservation d'hôtel sera annulée ou non.

Étape 1 :  Collecte des données

1.1 Importation des bibliothèques

In [3]:
# Importation des bibliothèques

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

1.2 Chargement des données

In [4]:
# Chargement des données

df = pd.read_csv(r"C:\Users\Administrator\Downloads\hotel_bookings.csv")

Étape 2 : Exploration des données (EDA)

2.1 Aperçu des données

In [5]:
# Afficher les 5 premières lignes

df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

2.2 Dimensions du dataset

In [6]:
# Taille du jeu de données

df.shape

(119390, 32)

2.3 Informations générales sur les données

In [7]:
# Informations générales sur le jeu de données

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

2.4 Vérification des valeurs manquantes

In [8]:
# Vérifier les valeurs manquantes

df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

2.5 Statistiques descriptives

In [9]:
# Statistiques descriptives des variables numériques

df.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

2.6 Verifier les doublons

In [10]:
# Vérifier le nombre de lignes dupliquées
df.duplicated().sum()

np.int64(31994)

Étape 3 : Pré-traitement des données

3.1 Suppression des doublons

In [11]:
# Suppression des doublons

df = df.drop_duplicates()

In [12]:
# Vérifier le nombre de lignes après suppression

df.shape

(87396, 32)

In [13]:
# Vérifier qu'il ne reste plus de doublons

df.duplicated().sum()

np.int64(0)

3.2 Analyse des valeurs manquantes

In [14]:
# Nombre et pourcentage des valeurs manquantes

missing = pd.DataFrame({
    'Valeurs manquantes': df.isnull().sum(),
    'Pourcentage (%)': round(df.isnull().mean()*100,2)
})

missing[missing['Valeurs manquantes'] > 0].sort_values(
    by='Valeurs manquantes',
    ascending=False
)

          Valeurs manquantes  Pourcentage (%)
company                82137            93.98
agent                  12193            13.95
country                  452             0.52
children                   4             0.00

3.3  Implementation du traitement des valeurs manquantes

3.3.1 Suppression de la colonne "company"

In [15]:
# Suppression de la colonne company
df = df.drop(columns=['company'])

In [16]:
# Vérifier que la colonne a été supprimée
'company' in df.columns

False

 3.3.2 Traitement de la variable children

Suppression des lignes contenant des valeurs manquantes dans la variable "children"

In [18]:
# Suppression des lignes contenant des valeurs manquantes
df = df.dropna(subset=['children'])

In [19]:
# Vérification
df['children'].isnull().sum()

np.int64(0)

3.3.3 Traitement de la variable "country"

Remplacement des valeurs manquantes par la modalité la plus fréquente (Mode)

In [21]:
# Afficher la valeur la plus fréquente
df['country'].mode()

0    PRT
Name: country, dtype: object

In [23]:
# Remplacer les valeurs manquantes par le mode
df['country'] = df['country'].fillna(df['country'].mode()[0])

In [24]:
# Vérification
df['country'].isnull().sum()

np.int64(0)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87392 entries, 0 to 119389
Data columns (total 31 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           87392 non-null  object
 1   is_canceled                     87392 non-null  int64
 2   lead_time                       87392 non-null  int64
 3   arrival_date_year               87392 non-null  int64
 4   arrival_date_month              87392 non-null  object
 5   arrival_date_week_number        87392 non-null  int64
 6   arrival_date_day_of_month       87392 non-null  int64
 7   stays_in_weekend_nights         87392 non-null  int64
 8   stays_in_week_nights            87392 non-null  int64
 9   adults                          87392 non-null  int64
 10  children                        87392 non-null  float64
 11  babies                          87392 non-null  int64
 12  meal                            87392 non-null  object
 13  country                         87392 non-null  object
 14  market_segment                  87392 non-null  object
 15  distribution_channel            87392 non-null  object
 16  is_repeated_guest               87392 non-null  int64
 17  previous_cancellations          87392 non-null  int64
 18  previous_bookings_not_canceled  87392 non-null  int64
 19  reserved_room_type              87392 non-null  object
 20  assigned_room_type              87392 non-null  object
 21  booking_changes                 87392 non-null  int64
 22  deposit_type                    87392 non-null  object
 23  agent                           75201 non-null  float64
 24  days_in_waiting_list            87392 non-null  int64
 25  customer_type                   87392 non-null  object
 26  adr                             87392 non-null  float64
 27  required_car_parking_spaces     87392 non-null  int64
 28  total_of_special_requests       87392 non-null  int64
 29  reservation_status              87392 non-null  object
 30  reservation_status_date         87392 non-null  object
dtypes: float64(3), int64(16), object(12)
memory usage: 21.3+ MB

3.3.4 Traitement de la variable "agent"

Analyse de la variable "agent" avant le traitement

In [26]:
# Nombre de valeurs différentes
df['agent'].nunique()

333

In [27]:
# Les valeurs les plus fréquentes
df['agent'].value_counts().head(10)

agent
9.0      28758
240.0    13028
14.0      3348
7.0       3300
250.0     2779
241.0     1644
28.0      1502
8.0       1383
1.0       1232
6.0       1117
Name: count, dtype: int64

In [28]:
# Pourcentage des valeurs manquantes
round(df['agent'].isnull().mean()*100,2)

np.float64(13.95)

Décision

La variable agent représente un identifiant d'agent et non une mesure numérique.
Les valeurs manquantes sont remplacées par 0 afin de représenter les réservations effectuées sans agent.

In [29]:
# Remplacer les valeurs manquantes par 0
df['agent'] = df['agent'].fillna(0)

In [30]:
# Vérification
df['agent'].isnull().sum()

np.int64(0)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87392 entries, 0 to 119389
Data columns (total 31 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           87392 non-null  object
 1   is_canceled                     87392 non-null  int64
 2   lead_time                       87392 non-null  int64
 3   arrival_date_year               87392 non-null  int64
 4   arrival_date_month              87392 non-null  object
 5   arrival_date_week_number        87392 non-null  int64
 6   arrival_date_day_of_month       87392 non-null  int64
 7   stays_in_weekend_nights         87392 non-null  int64
 8   stays_in_week_nights            87392 non-null  int64
 9   adults                          87392 non-null  int64
 10  children                        87392 non-null  float64
 11  babies                          87392 non-null  int64
 12  meal                            87392 non-null  object
 13  country                         87392 non-null  object
 14  market_segment                  87392 non-null  object
 15  distribution_channel            87392 non-null  object
 16  is_repeated_guest               87392 non-null  int64
 17  previous_cancellations          87392 non-null  int64
 18  previous_bookings_not_canceled  87392 non-null  int64
 19  reserved_room_type              87392 non-null  object
 20  assigned_room_type              87392 non-null  object
 21  booking_changes                 87392 non-null  int64
 22  deposit_type                    87392 non-null  object
 23  agent                           87392 non-null  float64
 24  days_in_waiting_list            87392 non-null  int64
 25  customer_type                   87392 non-null  object
 26  adr                             87392 non-null  float64
 27  required_car_parking_spaces     87392 non-null  int64
 28  total_of_special_requests       87392 non-null  int64
 29  reservation_status              87392 non-null  object
 30  reservation_status_date         87392 non-null  object
dtypes: float64(3), int64(16), object(12)
memory usage: 21.3+ MB

3.3.5 Vérification finale des valeurs manquantes

In [33]:
# Vérification finale
df.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
dtype: int64

 Étape 4 : Transformation des données

 4.1 Analyse des variables

In [34]:
# Liste des colonnes
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [35]:
# Nombre de colonnes
len(df.columns)

31

 4.2 Suppression des variables de fuite d'information

In [36]:
# Colonnes provoquant une fuite d'information

leakage_columns = [
    'reservation_status',
    'reservation_status_date'
]

leakage_columns

['reservation_status', 'reservation_status_date']

In [37]:
# Suppression des variables de fuite

df = df.drop(columns=leakage_columns)

df.shape

(87392, 29)

In [38]:
# Vérification

df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests'],
      dtype='object')

 4.3 Analyse des variables catégorielles

In [39]:
# Variables catégorielles

categorical_columns = df.select_dtypes(include='object').columns

categorical_columns

Index(['hotel', 'arrival_date_month', 'meal', 'country', 'market_segment',
       'distribution_channel', 'reserved_room_type', 'assigned_room_type',
       'deposit_type', 'customer_type'],
      dtype='object')

In [40]:
# Nombre des variables catégorielles

len(categorical_columns)

10

4.3.1 Analyse des modalités

In [41]:
# Nombre de modalités pour chaque variable catégorielle

for col in categorical_columns:
    print(f"{col} : {df[col].nunique()} modalités")

hotel : 2 modalités
arrival_date_month : 12 modalités
meal : 5 modalités
country : 177 modalités
market_segment : 7 modalités
distribution_channel : 5 modalités
reserved_room_type : 10 modalités
assigned_room_type : 12 modalités
deposit_type : 3 modalités
customer_type : 4 modalités

4.3.2Choix de la méthode d'encodage

Décision :

Les variables catégorielles doivent être transformées avant le développement du modèle, car les algorithmes de classification ne peuvent pas utiliser directement des valeurs textuelles.

Nous allons utiliser le One-Hot Encoding afin de transformer les modalités en variables binaires sans créer un ordre artificiel entre les catégories.

In [43]:
# Vérifier les variables catégorielles à encoder
categorical_columns

Index(['hotel', 'arrival_date_month', 'meal', 'country', 'market_segment',
       'distribution_channel', 'reserved_room_type', 'assigned_room_type',
       'deposit_type', 'customer_type'],
      dtype='object')

In [44]:
# Encodage des variables catégorielles
df = pd.get_dummies(df, columns=categorical_columns, drop_first=True)

In [45]:
# Vérification des dimensions après l'encodage
df.shape

(87392, 246)

In [46]:
# Vérification des premières lignes
df.head()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,...,assigned_room_type_H,assigned_room_type_I,assigned_room_type_K,assigned_room_type_L,assigned_room_type_P,deposit_type_Non Refund,deposit_type_Refundable,customer_type_Group,customer_type_Transient,customer_type_Transient-Party
0,0,342,2015,27,1,0,0,2,0.0,0,...,False,False,False,False,False,False,False,False,True,False
1,0,737,2015,27,1,0,0,2,0.0,0,...,False,False,False,False,False,False,False,False,True,False
2,0,7,2015,27,1,0,1,1,0.0,0,...,False,False,False,False,False,False,False,False,True,False
3,0,13,2015,27,1,0,1,1,0.0,0,...,False,False,False,False,False,False,False,False,True,False
4,0,14,2015,27,1,0,2,2,0.0,0,...,False,False,False,False,False,False,False,False,True,False

 Étape 5 : Préparation des données

5.1 Séparation des variables explicatives et de la variable cible

Décision :

La variable cible est **is_canceled**.

Toutes les autres variables seront utilisées comme variables explicatives pour entraîner le modèle de classification.

In [47]:
# Variable cible
y = df['is_canceled']

# Variables explicatives
X = df.drop(columns=['is_canceled'])

In [48]:
# Vérification
X.shape, y.shape

((87392, 245), (87392,))

 5.2 Séparation des données d'entraînement et de test

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [51]:
print("Train :", X_train.shape)
print("Test  :", X_test.shape)

Train : (69913, 245)
Test  : (17479, 245)

Étape 6 : Développement des modèles de Classification

 6.1 Choix du premier modèle

Décision :

Avant d'utiliser des modèles complexes comme Decision Tree ou Random Forest, il est recommandé de commencer par un modèle simple servant de référence (Baseline Model).

Nous choisissons donc **Logistic Regression**, car il est rapide, facile à interpréter et largement utilisé dans les problèmes de classification binaire.

Ce modèle permettra d'obtenir une première évaluation des performances avant de comparer avec des modèles plus avancés.

6.2 Importation des bibliothèques

In [52]:
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

 6.3 Construction du modèle

In [53]:
# Création du modèle
log_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

Explication :

Le nombre d'itérations est augmenté à 1000 afin d'assurer la convergence du modèle, car le jeu de données contient un grand nombre de variables après le One-Hot Encoding.

6.4 Entraînement du modèle

In [ ]:
# Entraîner le modèle

log_model.fit(X_train, y_train)

6.5 Vérification

In [56]:
log_model

LogisticRegression(max_iter=1000, random_state=42)

Étape 7 : Évaluation du modèle

 7.1 Prédiction

Décision :

Après l'entraînement du modèle, nous utilisons les données de test afin d'évaluer sa capacité de généralisation sur des observations jamais vues auparavant.

In [58]:
# Prédictions sur les données de test

y_pred = log_model.predict(X_test)

In [59]:
y_pred[:10]

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [60]:
log_model

LogisticRegression(max_iter=1000, random_state=42)

7.2 Accuracy

In [61]:
# Accuracy du modèle

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy :", round(accuracy,4))

Accuracy : 0.7783

7.3 Matrice de confusion

In [62]:
# Matrice de confusion

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[11664  1011]
 [ 2864  1940]]

7.4 Rapport de classification

In [63]:
# Rapport de classification

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.92      0.86     12675
           1       0.66      0.40      0.50      4804

    accuracy                           0.78     17479
   macro avg       0.73      0.66      0.68     17479
weighted avg       0.76      0.78      0.76     17479

 Étape 8 : Construction du modèle Decision Tree

8.1 Choix du deuxième modèle

Décision :

Après avoir utilisé Logistic Regression comme modèle de base, nous allons tester un modèle plus flexible : Decision Tree.

Ce modèle permet de mieux capturer des relations non linéaires entre les variables et la variable cible. Il est aussi facile à interpréter, car il fonctionne sous forme de règles de décision.

 8.2 Importation de la bibliothèque

In [64]:
from sklearn.tree import DecisionTreeClassifier

 8.3 Construction du modèle

In [66]:
# Création du modèle Decision Tree

tree_model = DecisionTreeClassifier(
    random_state=42
)

8.4 Entraînement du modèle

In [68]:
## Entraîner le modèle

tree_model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

 8.5 Vérification

In [69]:
tree_model

DecisionTreeClassifier(random_state=42)

Étape 9 : Évaluation du modèle Decision Tree


9.1 Prédiction

In [ ]:
# Prédictions sur les données de test

tree_pred = tree_model.predict(X_test)



Vérification

In [71]:
tree_pred[:10]

array([1, 0, 0, 0, 0, 1, 0, 1, 0, 0])



9.2 Accuracy

In [72]:
tree_accuracy = accuracy_score(y_test, tree_pred)

print("Accuracy :", round(tree_accuracy,4))

Accuracy : 0.7985



9.3 Matrice de confusion

In [73]:
tree_cm = confusion_matrix(y_test, tree_pred)

print(tree_cm)

[[10881  1794]
 [ 1728  3076]]

9.4 Rapport de classification

In [74]:
print(classification_report(y_test, tree_pred))

              precision    recall  f1-score   support

           0       0.86      0.86      0.86     12675
           1       0.63      0.64      0.64      4804

    accuracy                           0.80     17479
   macro avg       0.75      0.75      0.75     17479
weighted avg       0.80      0.80      0.80     17479

Étape 10 : Construction du modèle Random Forest

10.1 Choix du modèle

Décision :

Le modèle Decision Tree a donné de meilleurs résultats que la Logistic Regression.

Cependant, un seul arbre de décision peut être sensible aux variations des données et conduire à un surapprentissage.

Nous choisissons donc Random Forest, qui combine plusieurs arbres de décision afin d'améliorer la précision, la stabilité et la capacité de généralisation du modèle.

10.2 Importation des bibliothèques

In [76]:
from sklearn.ensemble import RandomForestClassifier



10.3 Construction du modèle

In [78]:
# Création du modèle Random Forest

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

Explication :

Le modèle Random Forest est composé de plusieurs arbres de décision.

Nous utilisons 100 arbres afin d'obtenir un bon compromis entre les performances et le temps de calcul.

Le paramètre random_state=42 garantit la reproductibilité des résultats.



10.4 Entraînement du modèle

In [81]:
# Entraîner le modèle

rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)



10.5 Vérification

In [82]:
rf_model

RandomForestClassifier(random_state=42)

Étape 11 : Évaluation du modèle Random Forest

11.1 Prédiction

Décision :

Après l'entraînement du modèle Random Forest, nous utilisons les données de test afin d'évaluer sa capacité de généralisation sur des données jamais vues auparavant.

In [83]:
# Prédictions sur les données de test

rf_pred = rf_model.predict(X_test)

In [84]:
# Verification
rf_pred[:10]

array([1, 1, 0, 1, 0, 0, 0, 0, 0, 0])

11.2 Accuracy

L'Accuracy représente la proportion des prédictions correctes réalisées par le modèle sur les données de test.

In [85]:
# Accuracy du modèle

rf_accuracy = accuracy_score(y_test, rf_pred)

print("Accuracy :", round(rf_accuracy,4))

Accuracy : 0.8507

11.3 Matrice de confusion

La matrice de confusion permet de comparer les valeurs réelles avec les valeurs prédites afin d'identifier les bonnes et les mauvaises classifications.

In [86]:
# Matrice de confusion

rf_cm = confusion_matrix(y_test, rf_pred)

print(rf_cm)

[[11787   888]
 [ 1722  3082]]



11.4 Rapport de classification

11.4 Rapport de classification

Le rapport de classification présente les principales métriques de performance :

- Precision
- Recall
- F1-score

Ces indicateurs permettent d'évaluer la qualité du modèle pour chaque classe.

In [87]:
# Rapport de classification

print(classification_report(y_test, rf_pred))

              precision    recall  f1-score   support

           0       0.87      0.93      0.90     12675
           1       0.78      0.64      0.70      4804

    accuracy                           0.85     17479
   macro avg       0.82      0.79      0.80     17479
weighted avg       0.85      0.85      0.85     17479

Étape 12 : Comparaison des modèles

Objectif :

Comparer les performances des différents modèles développés afin de sélectionner le meilleur modèle pour la prédiction des annulations de réservation.



12.2 Tableau comparatif

In [88]:
import pandas as pd

comparaison = pd.DataFrame({

    "Modèle":[
        "Logistic Regression",
        "Decision Tree",
        "Random Forest"
    ],

    "Accuracy":[
        accuracy,
        tree_accuracy,
        rf_accuracy
    ]

})

comparaison

                Modèle  Accuracy
0  Logistic Regression  0.778305
1        Decision Tree  0.798501
2        Random Forest  0.850678

12.3 Meilleur modèle

Analyse :

Le modèle Random Forest obtient la meilleure précision parmi les trois modèles.

Il sera retenu comme modèle final du projet.

12.4 Identifier automatiquement le meilleur modèle

In [89]:
best_model = comparaison.loc[comparaison["Accuracy"].idxmax()]

best_model

Modèle      Random Forest
Accuracy         0.850678
Name: 2, dtype: object



12.5 Conclusion

Conclusion :

Après comparaison des trois modèles de classification, le modèle Random Forest présente les meilleures performances avec une Accuracy de 85 %.

Il offre également un meilleur équilibre entre la précision et la capacité de généralisation.

Nous retenons donc ce modèle comme modèle final pour prédire les annulations des réservations hôtelières.